on: [push]
jobs:
#  format:
#    runs-on: nix
#    steps:
#      - uses: actions/checkout@v4
#      - run: nix --experimental-features 'nix-command flakes' fmt
  build:
    runs-on: nix
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v4
      - run: nix --experimental-features 'nix-command flakes' flake update
      - run: nixos-rebuild --experimental-features 'nix-command flakes' build --flake .#Haven
      - run: nixos-rebuild --experimental-features 'nix-command flakes' build --flake .#Khanda
