on: [push]
jobs:
  format:
    runs-on: nix
    steps:
      - run: nix --experimental-features 'nix-command flakes' fmt
  build:
    runs-on: nix
    steps:
      - run: nix --experimental-features 'nix-command flakes' flake update
      - run: nixos-rebuild --experimental-features 'nix-command flakes' build --flake .#Haven
      - run: nixos-rebuild --experimental-features 'nix-command flakes' build --flake .#Khanda